version: '3'

services:
  postgres:
    image: postgres:15.13-alpine
    container_name: pix-api-postgres
    ports:
      - '${PIX_DATABASE_PORT:-5432}:5432'
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: redis:7.2.9-alpine
    container_name: pix-api-redis
    ports:
      - '${PIX_CACHE_PORT:-6379}:6379'

